# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEnquiry():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_enquiry(self):
    self.driver.get("http://localhost:8004/")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.CSS_SELECTOR, "li > img").click()
    self.driver.find_element(By.LINK_TEXT, "Category").click()
    self.driver.find_element(By.LINK_TEXT, "Religious Tours").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > td:nth-child(1) tr:nth-child(3) > td").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > td:nth-child(1) font").click()
    self.driver.find_element(By.CSS_SELECTOR, "font").click()
    self.driver.find_element(By.NAME, "sbmt").click()
    self.driver.find_element(By.NAME, "t1").click()
    self.driver.find_element(By.NAME, "t1").send_keys("Aakash")
    self.driver.find_element(By.NAME, "t2").click()
    self.driver.find_element(By.NAME, "t2").send_keys("1235678")
    self.driver.find_element(By.NAME, "t3").click()
    self.driver.find_element(By.NAME, "t3").send_keys("fgsjdgj@mail.com")
    self.driver.find_element(By.NAME, "t4").click()
    self.driver.find_element(By.NAME, "t2").click()
    self.driver.find_element(By.NAME, "t2").send_keys("1235678567")
    self.driver.find_element(By.NAME, "t4").send_keys("1")
    self.driver.find_element(By.NAME, "t4").click()
    self.driver.find_element(By.NAME, "t4").send_keys("2")
    self.driver.find_element(By.NAME, "t4").click()
    element = self.driver.find_element(By.NAME, "t4")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.NAME, "t5").click()
    self.driver.find_element(By.NAME, "t5").send_keys("4")
    self.driver.find_element(By.NAME, "t6").click()
    self.driver.find_element(By.NAME, "t6").send_keys("3")
    self.driver.find_element(By.NAME, "t7").click()
    self.driver.find_element(By.NAME, "t7").send_keys("i want to enquire about it quickly")
    self.driver.find_element(By.NAME, "sbmt").click()
  
