# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestContact():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_contact(self):
    self.driver.get("http://localhost:8004/")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.LINK_TEXT, "Contact").click()
    self.driver.find_element(By.NAME, "t1").click()
    self.driver.find_element(By.NAME, "t1").send_keys("Levi Ackerman")
    self.driver.find_element(By.NAME, "t2").click()
    self.driver.find_element(By.NAME, "t2").send_keys("1209348745")
    self.driver.find_element(By.NAME, "t3").click()
    self.driver.find_element(By.NAME, "t3").send_keys("ackerman.levi4.5@gmail.com")
    self.driver.find_element(By.NAME, "t4").click()
    self.driver.find_element(By.NAME, "t4").send_keys("Is there a tour for for rehabilitation for my injuries")
    self.driver.find_element(By.NAME, "sbmt").click()
  
